In [1]:
%load_ext lab_black

In [2]:
import numpy as np

# zipオブジェクト

In [3]:
a1 = [1, 3, 5, 7, 9]
a2 = [2, 4, 6, 8, 10]
z = zip(a1, a2)
z

In [4]:
list(z)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

In [5]:
list(z)

[]

In [6]:
z = zip(a1, a2)
a = np.array(list(z))
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# 様々なデータ列を束ねる

In [7]:
z = zip(a1, "あいうえお")

In [8]:
list(z)

[(1, 'あ'), (3, 'い'), (5, 'う'), (7, 'え'), (9, 'お')]

In [9]:
z = zip("あいうえお", "かきくけこ", "さしすせそ")
list(z)

[('あ', 'か', 'さ'),
 ('い', 'き', 'し'),
 ('う', 'く', 'す'),
 ('え', 'け', 'せ'),
 ('お', 'こ', 'そ')]

## 辞書作成への応用

In [10]:
e = ["dog", "cat", "bird"]
j = ["犬", "猫", "鳥"]
z = zip(e, j)

In [11]:
d = dict(list(z))
d

{'dog': '犬', 'cat': '猫', 'bird': '鳥'}

## 繰り返し処理への応用

In [12]:
a1 = [1, 2, 3]
a2 = [4, 5, 6]
z = zip(a1, a2)

In [13]:
for x, y in z:
    print(x, "+", y, "=", x + y)

1 + 4 = 5
2 + 5 = 7
3 + 6 = 9


In [14]:
r = range(10)
r

range(0, 10)

In [15]:
list(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 要素の整列

In [16]:
a = np.array([3, 5, 1, 4, 2, 6])
a

array([3, 5, 1, 4, 2, 6])

## sort関数 元の配列を壊さない

In [17]:
a2 = np.sort(a)
a2

array([1, 2, 3, 4, 5, 6])

In [18]:
a

array([3, 5, 1, 4, 2, 6])

## sortメソッド 元の配列を変更する

In [19]:
a.sort()
a

array([1, 2, 3, 4, 5, 6])

In [23]:
a = np.array([3, 5, 1, 4, 2, 6])
a

array([3, 5, 1, 4, 2, 6])

## 逆順にする

In [24]:
a2 = np.sort(a)[::-1]
a2

array([6, 5, 4, 3, 2, 1])

In [25]:
a2 = np.flip(np.sort(a))
a2

array([6, 5, 4, 3, 2, 1])

# 整列後にインデックスを得る

In [26]:
a2 = a.argsort()
a2

array([2, 4, 0, 3, 1, 5])

In [27]:
a

array([3, 5, 1, 4, 2, 6])