In [5]:
%load_ext lab_black

# スライス（添字）の応用

In [1]:
import numpy as np

In [7]:
a = np.arange(20) * 2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [9]:
print(a[1:6])

[ 2  4  6  8 10]


# 配列形状の変形

In [10]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
a2 = a.reshape((5, 6))
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [13]:
a3 = a.reshape((2, 3, 5))
a3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [14]:
a3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
a3.ravel()  # 多次元のときはflattenより早そう

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# 配列の転置

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# スライスにリストや配列を与える

In [21]:
a = np.arange(10) * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
a2 = a[[1, 3, 5]]
a2

array([10, 30, 50])

In [23]:
a[[1, 3, 5]] = [7, 8, 9]
a

array([ 0,  7, 20,  8, 40,  9, 60, 70, 80, 90])

# 行、列の反転

In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.flip(a)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [28]:
print(np.flip(a, axis=0)) # axisはどれを軸に反転させるか

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [29]:
print(np.flip(a, axis=1))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


# 行、列の回転

In [32]:
np.roll(a, shift=1)

array([[9, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.roll(a, shift=1, axis=0)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.roll(a, shift=1, axis=1)

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

# 配列の連結

In [35]:
a1 = np.array([0, 1, 2])
a2 = np.array([3, 4, 5])
print(a1)
print(a2)

[0 1 2]
[3 4 5]


In [37]:
a = np.append(a1, a2)
a

array([0, 1, 2, 3, 4, 5])

In [38]:
a1 = np.zeros((2, 4))
a2 = np.ones((2, 4))
print(a1)
print(a2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
a = np.append(a1, a2, axis=0)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
a = np.append(a1, a2, axis=1)
a

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [44]:
a1 = np.zeros((2, 2))
a1.fill(1)
a2 = np.zeros((2, 2))
a2.fill(2)
a3 = np.zeros((2, 2))
a3.fill(3)
print(a1)
print(a2)
print(a3)

[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]
[[3. 3.]
 [3. 3.]]


In [46]:
a = np.concatenate((a1, a2, a3), axis=0) ## 3つ以上の配列の連結
a

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [3., 3.]])

In [47]:
a = np.concatenate((a1, a2, a3), axis=1)
a

array([[1., 1., 2., 2., 3., 3.],
       [1., 1., 2., 2., 3., 3.]])

In [48]:
a = np.vstack((a1, a2, a3))
a

array([[1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [3., 3.]])

In [49]:
a = np.hstack((a1, a2, a3))
a

array([[1., 1., 2., 2., 3., 3.],
       [1., 1., 2., 2., 3., 3.]])

# 配列の繰り返し

In [50]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [51]:
a2 = np.tile(a, (3, 1))
a2

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [52]:
a2 = np.tile(a, (1, 3))
a2

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

# 要素の挿入

In [53]:
a = np.array([0, 1, 2, 3, 4, 5])
ins = np.array([10, 20, 30])
print(a)
print(ins)

[0 1 2 3 4 5]
[10 20 30]


In [55]:
a2 = np.insert(a, 3, ins)
a2

array([ 0,  1,  2, 10, 20, 30,  3,  4,  5])

In [56]:
a2 = np.insert(a, 1, 99)
a2

array([ 0, 99,  1,  2,  3,  4,  5])

In [58]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ins = np.array([91, 92, 93])
print(a)
print(ins)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[91 92 93]


In [63]:
a2 = np.insert(a, 2, ins, axis=0)
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [91 92 93]
 [ 7  8  9]]


In [64]:
a2 = np.insert(a, 2, ins, axis=1)
print(a2)

[[ 1  2 91  3]
 [ 4  5 92  6]
 [ 7  8 93  9]]


# 要素の削除

In [65]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [67]:
a2 = np.delete(a, 2)
a2

array([0, 1, 3, 4, 5])

In [68]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
a2 = np.delete(a, 1, axis=0)
a2

array([[1, 2, 3],
       [7, 8, 9]])

In [70]:
a2 = np.delete(a, 1, axis=1)
a2

array([[1, 3],
       [4, 6],
       [7, 9]])

# 要素の抽出

## 予備演習

In [71]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [73]:
msk = [False, True, False, False]
a2 = a[msk]
a2

array([1])

In [74]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
m = a % 2 == 0
m

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

## 条件式による要素の抽出

In [77]:
a2 = a[a % 2 == 0]
a2

array([0, 2, 4, 6, 8])

In [78]:
a2 = a[a > 5]
a2

array([6, 7, 8, 9])

## whereによる狙い撃ち

In [79]:
a2 = np.where(a > 5, "biq", a)
a2

array(['0', '1', '2', '3', '4', '5', 'biq', 'biq', 'biq', 'biq'],
      dtype='<U21')

In [81]:
a2 = np.where(a % 2 == 0, "偶数", "奇数")
a2

array(['偶数', '奇数', '偶数', '奇数', '偶数', '奇数', '偶数', '奇数', '偶数', '奇数'],
      dtype='<U2')

## 最大値、最小値

In [83]:
a = np.array([1, 2, 3, 4, 3, 2, 1])
a

array([1, 2, 3, 4, 3, 2, 1])

In [84]:
a.max()

4

In [85]:
a.min()

1